### ISSUE TITLE
Use graph processing technologies for more LDBC work

### ISSUE THREAD

**Issue by annainfo** [ldbc/ldbc.github.io#26]
The first sentence of https://ldbcouncil.org/introduction/ (https://github.com/ldbc/ldbc.github.io/blob/main/content/english/introduction.md) :

"The Linked Data Benchmark Council (LDBC) is a non-profit organization aiming to define standard graph benchmarks to foster a community around graph processing technologies."

Proposal: 
1) Store the website content as data in a graph database and use "graph processing technologies" to create a website from that data.
2) Define "standard graph benchmarks" in the same graph database.

By doing so 
1) "foster a community around graph processing technologies" 
2) increase consistency on the website
3) solve https://github.com/ldbc/ldbc.github.io/issues/17 which suggests using a "YAML file", which seems to be a step in the direction of structured and maybe linked data.

**Comment by annainfo** [comment]
https://terminusdb.com/blog/terminusdb-a-headless-cms/ 2022-11-15 "TerminusDB a headless CMS? That’s correct, you read it right."

**Comment by szarnyasg** [comment]
Thanks for the suggestion. We spent a significant amount of development resources for creating our current toolchains for deploying the website, generating the LaTeX code/PDF of the specification documents, etc., and they work reasonably well. I cannot justify the effort of reimplementing these in a graph database.
